artifakt_version: "0.2"
tag: "0.1.9"
build_engine: "terraform"
available_regions:
  - us-east-1
infrastructure:
  build_time: 1
  cost_estimation: 
    monthly_price: 1
    details: "almost free infra"
actions:
  -
    name: dummy
    code: dummy
    script: dummy.sh
    engine: shell
  -
    code: deploy
    name: Deploy
    description: Deploy VSF Stack on docker host
    category: applications
    engine: shell
    script: deploy.sh
    params:
    -
     code: need_import
     name: Import requis
     type: text
     required: false
     default: Yes
     validation:
        values:
          - Yes
          - No
  -
    code: deployooo
    name: Deploy
    description: Deploy VSF Stack on docker host
    category: applications
    engine: shell
    script: deploy.sh
    params:
    -
     code: need_import
     name: Import requis
     type: text
     required: false
     default: tata
     validation:
        values:
          - tata
          - toto
outputs:
  -
    name: dummy
    code: dummy
  -
    name: dummy secret
    code: dummy_secret
    secret: true
  -
    name: new dummy
    code: new_dummy
    secret: false
